theme = "catppuccin_mocha"

[editor]
# Disabled due to weird rendering on window focus
#line-number = "relative"
mouse = true
cursorline = true
true-color = true
color-modes = true
completion-timeout = 150

[editor.statusline]
separator = ">"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true
skip-levels = 1

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
ignore = true

[editor.lsp]
display-messages = true
snippets = true
display-inlay-hints = true

[keys.normal]
C-s = ":w"

[keys.insert]
j = { j = "normal_mode" }
