[[language]]
name = "go"
language-servers = ["gopls","helix-snippets-ls"]
auto-format = true

scope = "source.go"
injection-regex = "go"
file-types = ["go"]
roots = ["go.mod",".git"]
comment-token="//"

[language-server.vscode-json-language-server]
command = "vscode-json-languageserver"
args = ["--stdio"]

[[language]]
name = "json"
language-servers = ["vscode-json-language-server"]
auto-format = true
scope = "source.json"
file-types = ["json"]




