## GO ------------------------------------------------------------------------------
[language-server.gopls]
config = { gofumpt = true, experimentalPostfixCompletions = true, usePlaceholders = true }

[[language]]
name = "go"
scope = "source.go"
injection-regex = "go"
file-types = ["go"]
roots = ["go.mod", "go.sum"]
auto-format = true
comment-token = "//"
formatter = ["gofumpt"]
language-servers = ["gopls"]

## TOML ----------------------------------------------------------------------------
[[language]]
name = "toml"
scope = "scope.toml"
injection-regex = "toml"
file-types = ["toml"]
auto-format = true
comment-token = "#"
formatter = { command = "taplo", args = ["fmt", "-"] }
language-servers = ["taplo"]
