[[language]]
name = "go"
language-servers = ["gopls","helix-snippets-ls"]
auto-format = true

scope = "source.go"
injection-regex = "go"
file-types = ["go"]
roots = ["go.mod",".git"]
comment-token="//"


